services:
  - type: web
    name: cybercafe
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ADMIN_EMAIL
        sync: false
      - key: PAYMENT_UPI_ID
        sync: false
      - key: PAYMENT_RECEIVER
        sync: false
      - key: PAYMENT_QR_IMAGE_URL
        sync: false